In [1]:
import requests
import pandas as pd
import numpy as np

%matplotlib inline

In [2]:
df = pd.read_json('https://data.cityofnewyork.us/resource/qiz3-axqb.json')

In [3]:
# Looks like there's 2 days and 1000 samples worth of data
df['date'].describe()

count                    1000
unique                      2
top       2019-05-11 00:00:00
freq                      561
first     2019-05-10 00:00:00
last      2019-05-11 00:00:00
Name: date, dtype: object

In [4]:
df.dtypes

:@computed_region_92fq_4b7q             float64
:@computed_region_efsh_h5xi             float64
:@computed_region_f5dn_yrer             float64
:@computed_region_sbqj_enih             float64
:@computed_region_yeji_bk3q             float64
borough                                  object
contributing_factor_vehicle_1            object
contributing_factor_vehicle_2            object
contributing_factor_vehicle_3            object
contributing_factor_vehicle_4            object
contributing_factor_vehicle_5            object
cross_street_name                        object
date                             datetime64[ns]
latitude                                float64
location                                 object
longitude                               float64
number_of_cyclist_injured                 int64
number_of_cyclist_killed                  int64
number_of_motorist_injured                int64
number_of_motorist_killed                 int64
number_of_pedestrians_injured             int64
number_of_pedestrians_killed              int64
number_of_persons_injured                 int64
number_of_persons_killed                  int64
off_street_name                          object
on_street_name                           object
time                                     object
unique_key                                int64
vehicle_type_code1                       object
vehicle_type_code2                       object
vehicle_type_code_3                      object
vehicle_type_code_4                      object
vehicle_type_code_5                      object
zip_code                                float64
dtype: object

In [5]:
df.head()

,:@computed_region_92fq_4b7q,:@computed_region_efsh_h5xi,:@computed_region_f5dn_yrer,:@computed_region_sbqj_enih,:@computed_region_yeji_bk3q,borough,contributing_factor_vehicle_1,contributing_factor_vehicle_2,contributing_factor_vehicle_3,contributing_factor_vehicle_4,...,off_street_name,on_street_name,time,unique_key,vehicle_type_code1,vehicle_type_code2,vehicle_type_code_3,vehicle_type_code_4,vehicle_type_code_5,zip_code
0,40.0,11608.0,29.0,30.0,5.0,BRONX,Unspecified,NaN,NaN,NaN,...,NaN,NaN,19:00,4131073,Sedan,NaN,NaN,NaN,NaN,10470.0
1,29.0,11272.0,48.0,33.0,5.0,BRONX,Unspecified,NaN,NaN,NaN,...,PEROT STREET,SEDGWICK AVENUE,18:32,4130167,Sedan,NaN,NaN,NaN,NaN,10463.0
2,31.0,11611.0,58.0,26.0,5.0,BRONX,Unsafe Speed,Unspecified,NaN,NaN,...,BRUCKNER BOULEVARD,LELAND AVENUE,16:30,4130078,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN,10473.0
3,8.0,13825.0,5.0,38.0,2.0,BROOKLYN,Failure to Yield Right-of-Way,Unspecified,NaN,NaN,...,PEARSON STREET,AVENUE U,16:08,4130829,Sedan,Sedan,NaN,NaN,NaN,11234.0
4,NaN,NaN,NaN,NaN,NaN,BRONX,Traffic Control Disregarded,Unspecified,NaN,NaN,...,SOUTHERN BOULEVARD,EAST FORDHAM ROAD,22:48,4129854,Taxi,Sedan,NaN,NaN,NaN,10458.0

In [6]:
# Let's see a random column
df.loc[np.random.randint(0,100)]

:@computed_region_92fq_4b7q                                                     23
:@computed_region_efsh_h5xi                                                  12422
:@computed_region_f5dn_yrer                                                     20
:@computed_region_sbqj_enih                                                     15
:@computed_region_yeji_bk3q                                                      4
borough                                                                  MANHATTAN
contributing_factor_vehicle_1                       Driver Inattention/Distraction
contributing_factor_vehicle_2                                          Unspecified
contributing_factor_vehicle_3                                                  NaN
contributing_factor_vehicle_4                                                  NaN
contributing_factor_vehicle_5                                                  NaN
cross_street_name                         801       AMSTERDAM AVENUE
date                                                           2019-05-11 00:00:00
latitude                                                                   40.7962
location                         {'type': 'Point', 'coordinates': [-73.968796, ...
longitude                                                                 -73.9688
number_of_cyclist_injured                                                        0
number_of_cyclist_killed                                                         0
number_of_motorist_injured                                                       0
number_of_motorist_killed                                                        0
number_of_pedestrians_injured                                                    0
number_of_pedestrians_killed                                                     0
number_of_persons_injured                                                        0
number_of_persons_killed                                                         0
off_street_name                                                                NaN
on_street_name                                                                 NaN
time                                                                         18:15
unique_key                                                                 4131472
vehicle_type_code1                                                           Sedan
vehicle_type_code2                             Station Wagon/Sport Utility Vehicle
vehicle_type_code_3                                                            NaN
vehicle_type_code_4                                                            NaN
vehicle_type_code_5                                                            NaN
zip_code                                                                     10025
Name: 80, dtype: object

In [7]:
# Let's drop some columns that we won't use
drop_cols = [col for col in df.columns if col[0] == ':']
drop_cols += ['location', ]
df.drop(drop_cols, axis=1, inplace=True)

In [8]:
# Looks like the street names need to be stripped
for col in ['cross_street_name', 'off_street_name', 'on_street_name']:
    df[col] = df[col].str.strip()

In [13]:
# create lat, long col
df['coordinates'] = df['latitude'].astype(str) + ', ' + df['longitude'].astype(str)

In [14]:
df.loc[1]

borough                                         BRONX
contributing_factor_vehicle_1             Unspecified
contributing_factor_vehicle_2                     NaN
contributing_factor_vehicle_3                     NaN
contributing_factor_vehicle_4                     NaN
contributing_factor_vehicle_5                     NaN
cross_street_name                                 NaN
date                              2019-05-11 00:00:00
latitude                                      40.8766
longitude                                    -73.8996
number_of_cyclist_injured                           0
number_of_cyclist_killed                            0
number_of_motorist_injured                          0
number_of_motorist_killed                           0
number_of_pedestrians_injured                       0
number_of_pedestrians_killed                        0
number_of_persons_injured                           0
number_of_persons_killed                            0
off_street_name                          PEROT STREET
on_street_name                        SEDGWICK AVENUE
time                                            18:32
unique_key                                    4130167
vehicle_type_code1                              Sedan
vehicle_type_code2                                NaN
vehicle_type_code_3                               NaN
vehicle_type_code_4                               NaN
vehicle_type_code_5                               NaN
zip_code                                        10463
coordinates                      40.876606, -73.89959
Name: 1, dtype: object

In [43]:
df.to_pickle('data.pkl')

In [44]:
df1 = pd.read_pickle('data.pkl')

In [45]:
df1

,borough,contributing_factor_vehicle_1,contributing_factor_vehicle_2,contributing_factor_vehicle_3,contributing_factor_vehicle_4,contributing_factor_vehicle_5,cross_street_name,date,latitude,longitude,...,off_street_name,on_street_name,time,unique_key,vehicle_type_code1,vehicle_type_code2,vehicle_type_code_3,vehicle_type_code_4,vehicle_type_code_5,zip_code
0,BRONX,Unspecified,NaN,NaN,NaN,NaN,4401 WHITE PLAINS ROAD,2019-05-11,40.898685,-73.854120,...,NaN,NaN,19:00,4131073,Sedan,NaN,NaN,NaN,NaN,10470.0
1,BRONX,Unspecified,NaN,NaN,NaN,NaN,NaN,2019-05-11,40.876606,-73.899590,...,PEROT STREET,SEDGWICK AVENUE,18:32,4130167,Sedan,NaN,NaN,NaN,NaN,10463.0
2,BRONX,Unsafe Speed,Unspecified,NaN,NaN,NaN,NaN,2019-05-11,40.825966,-73.862175,...,BRUCKNER BOULEVARD,LELAND AVENUE,16:30,4130078,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN,10473.0
3,BROOKLYN,Failure to Yield Right-of-Way,Unspecified,NaN,NaN,NaN,NaN,2019-05-11,40.612580,-73.918300,...,PEARSON STREET,AVENUE U,16:08,4130829,Sedan,Sedan,NaN,NaN,NaN,11234.0
4,BRONX,Traffic Control Disregarded,Unspecified,NaN,NaN,NaN,NaN,2019-05-11,NaN,NaN,...,SOUTHERN BOULEVARD,EAST FORDHAM ROAD,22:48,4129854,Taxi,Sedan,NaN,NaN,NaN,10458.0
5,QUEENS,Backing Unsafely,NaN,NaN,NaN,NaN,78-11 80 STREET,2019-05-11,40.705257,-73.868580,...,NaN,NaN,16:10,4129863,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN,11385.0
6,BROOKLYN,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,NaN,2019-05-11,40.602478,-73.966360,...,OCEAN PARKWAY,AVENUE S,17:41,4130646,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,11223.0
7,QUEENS,Unspecified,Unspecified,NaN,NaN,NaN,104-43 121 STREET,2019-05-11,40.686580,-73.822290,...,NaN,NaN,17:00,4129921,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,11419.0
8,BROOKLYN,Other Vehicular,NaN,NaN,NaN,NaN,NaN,2019-05-11,40.696785,-73.956590,...,PARK AVENUE,BEDFORD AVENUE,3:17,4131493,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN,11205.0
9,QUEENS,Passing Too Closely,Unspecified,NaN,NaN,NaN,138-11 20 AVENUE,2019-05-11,40.781670,-73.829990,...,NaN,NaN,17:30,4129689,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,11356.0
10,QUEENS,Other Vehicular,Turning Improperly,NaN,NaN,NaN,NaN,2019-05-11,40.680687,-73.844590,...,WOODHAVEN BOULEVARD,ROCKAWAY BOULEVARD,1:57,4129438,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN,11417.0
11,QUEENS,Driver Inexperience,Unspecified,NaN,NaN,NaN,NaN,2019-05-11,40.735497,-73.869705,...,57 AVENUE,92 STREET,15:55,4130277,Taxi,Sedan,NaN,NaN,NaN,11373.0
12,NaN,Driver Inattention/Distraction,Unsafe Speed,NaN,NaN,NaN,NaN,2019-05-11,NaN,NaN,...,WEBSTER AVENUE,EAST 165 STREET,15:30,4129744,Sedan,Sedan,NaN,NaN,NaN,NaN
13,NaN,Driver Inattention/Distraction,Unspecified,Unspecified,Unspecified,NaN,NaN,2019-05-11,40.608480,-74.013780,...,NaN,BAY 8 STREET,2:00,4129386,Sedan,Sedan,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN
14,QUEENS,Following Too Closely,Unspecified,NaN,NaN,NaN,82-48 WOODHAVEN BOULEVARD,2019-05-11,40.703075,-73.855316,...,NaN,NaN,21:40,4129870,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN,11385.0
15,NaN,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,NaN,2019-05-11,NaN,NaN,...,NaN,BROOKLYN QUEENS EXPRESSWAY RAMP,12:55,4131149,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
16,MANHATTAN,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,NaN,2019-05-11,40.713135,-74.004070,...,CHAMBERS STREET,CENTRE STREET,4:43,4130795,Sedan,NaN,NaN,NaN,NaN,10007.0
17,NaN,Other Vehicular,Other Vehicular,NaN,NaN,NaN,NaN,2019-05-11,40.816500,-73.946556,...,NaN,WEST 135 STREET,22:14,4130563,Taxi,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
18,NaN,Passing Too Closely,Passing Too Closely,NaN,NaN,NaN,NaN,2019-05-11,40.630820,-73.886360,...,SHORE PARKWAY,ROCKAWAY PARKWAY,10:45,4130774,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN,NaN
19,NaN,Unsafe Speed,NaN,NaN,NaN,NaN,NaN,2019-05-11,NaN,NaN,...,NaN,WHITESTONE EXPRESSWAY,11:35,4129549,Sedan,NaN,NaN,NaN,NaN,NaN
20,QUEENS,Other Vehicular,Unspecified,NaN,NaN,NaN,NaN,2019-05-11,40.780155,-73.840600,...,128 STREET,22 AVENUE,20:00,4129696,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN,11356.0
21,NaN,Unspecified,Unspecified,NaN,NaN,NaN,NaN,2019-05-11,40.712727,-73.728990,...,NaN,CROSS ISLAND PARKWAY,1:15,4129406,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
22,BRONX,Pavement Slippery,Unspecified,Unspecified,Unspecified,Unspecified,NaN,2019-05-11,40.843304,-73.919190,...,JESUP AVENUE,WEST 172 STREET,3:10,4130126,Sedan,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,Sedan,Station Wagon/Sport Utility Vehicle,10452.0
23,BROOKLYN,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,1000 WASHINGTON AVENUE,2019-05-11,40.666946,-73.961685,...,NaN,NaN,14:00,4130528,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,11225.0
24,BROOKLYN,Failure to Yield Right-of-Way,Unspecified,NaN,NaN,NaN,NaN,2019-05-11,40.616673,-73.925630,...,EAST 51 STREET,AVENUE O,12:18,4130848,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN,11234.0
25,NaN,Following Too Closely,Unspecified,NaN,NaN,NaN,NaN,2019-05-11,40.752052,-74.000984,...,NaN,10 AVENUE,17:02,4130738,Pick-up Truck,Pick-up Truck,NaN,NaN,NaN,NaN
26,BRONX,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,271 EAST 233 STREET,2019-05-11,40.896313,-73.868300,...,NaN,NaN,7:30,4131070,Sedan,NaN,NaN,NaN,NaN,10470.0
27,BROOKLYN,Fell Asleep,Unspecified,Unspecified,NaN,NaN,NaN,2019-05-11,40.701077,-73.940430,...,FLUSHING AVENUE,HUMBOLDT STREET,1:23,4129398,Sedan,Box Truck,Box Truck,NaN,NaN,11206.0
28,BROOKLYN,Backing Unsafely,Unspecified,NaN,NaN,NaN,NaN,2019-05-11,40.686977,-73.963520,...,GREENE AVENUE,CAMBRIDGE PLACE,10:00,4129521,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,11238.0
29,BROOKLYN,Unspecified,Unspecified,NaN,NaN,NaN,507 CONEY ISLAND AVENUE,2019-05-11,40.645435,-73.970580,...,NaN,NaN,16:50,4129612,Station Wagon/Sport Utility Vehicle,Bike,NaN,NaN,NaN,11218.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,NaN,Unspecified,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,NaN,NaN,...,NaN,QUEENSBORO BRIDGE LOWER,8:19,4129022,Taxi,Box Truck,NaN,NaN,NaN,NaN
971,QUEENS,Backing Unsafely,Unspecified,NaN,NaN,NaN,105-22 171 PLACE,2019-05-10,40.701775,-73.785490,...,NaN,NaN,18:50,4129376,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN,11433.0
972,BROOKLYN,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,2121 BEEKMAN PLACE,2019-05-10,40.660015,-73.960976,...,NaN,NaN,16:45,4129671,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN,11225.0
973,NaN,Drugs (illegal),Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.868110,-73.919760,...,NaN,BROADWAY,21:00,4130341,Sedan,Bus,NaN,NaN,NaN,NaN
974,QUEENS,Unsafe Lane Changing,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.666150,-73.805750,...,134 STREET,SOUTH CONDUIT AVENUE,17:00,4129295,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,11430.0
975,QUEENS,Following Too Closely,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.704082,-73.816410,...,HILLSIDE AVENUE,138 STREET,10:30,4129131,TRAIL,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,11435.0
976,QUEENS,Aggressive Driving/Road Rage,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.758274,-73.933360,...,CRESCENT STREET,36 AVENUE,1:30,4130410,Taxi,Sedan,NaN,NaN,NaN,11106.0
977,BRONX,Unspecified,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.910910,-73.905450,...,INDEPENDENCE AVENUE,WEST 261 STREET,14:57,4129194,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,10471.0
978,BROOKLYN,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,67 WHIPPLE STREET,2019-05-10,40.701603,-73.944250,...,NaN,NaN,19:35,4130568,NaN,NaN,NaN,NaN,NaN,11206.0
979,MANHATTAN,Following Too Closely,Unspecified,NaN,NaN,NaN,252 WEST 29 STREET,2019-05-10,40.748470,-73.994400,...,NaN,NaN,20:52,4130732,Sedan,Taxi,NaN,NaN,NaN,10001.0
980,MANHATTAN,Unspecified,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.709530,-74.008420,...,NASSAU STREET,JOHN STREET,14:30,4129173,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN,10038.0
981,BROOKLYN,Driver Inexperience,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.704120,-73.947876,...,LORIMER STREET,BROADWAY,16:00,4130534,Sedan,Pick-up Truck,NaN,NaN,NaN,11206.0
982,BROOKLYN,Unspecified,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.653362,-74.008900,...,40 STREET,3 AVENUE,10:30,4129281,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN,11232.0
983,NaN,Turning Improperly,Turning Improperly,NaN,NaN,NaN,NaN,2019-05-10,NaN,NaN,...,20 AVENUE,WHITESTONE EXPRESSWAY,18:00,4129340,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
984,NaN,Unspecified,Unspecified,Unspecified,NaN,NaN,NaN,2019-05-10,40.815525,-73.857790,...,NaN,BOLTON AVENUE,13:45,4129197,Sedan,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
985,BROOKLYN,Backing Unsafely,Unspecified,NaN,NaN,NaN,805 LENOX ROAD,2019-05-10,40.655396,-73.929920,...,NaN,NaN,19:57,4130244,Sedan,Sedan,NaN,NaN,NaN,11203.0
986,NaN,Unspecified,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.681347,-73.804344,...,115 AVENUE,VANWYCK EXPRESSWAY,16:08,4129263,Taxi,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
987,NaN,Unsafe Lane Changing,Unsafe Lane Changing,NaN,NaN,NaN,186 EAST HOUSTON STREET,2019-05-10,NaN,NaN,...,NaN,NaN,20:45,4129348,Taxi,Taxi,NaN,NaN,NaN,NaN
988,QUEENS,Passing Too Closely,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.664627,-73.849920,...,84 STREET,155 AVENUE,16:00,4131470,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN,11414.0
989,NaN,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.761040,-73.975380,...,NaN,EAST 54 STREET,7:00,4128882,Bus,Box Truck,NaN,NaN,NaN,NaN
990,BROOKLYN,Unspecified,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.649020,-74.006250,...,5 AVENUE,43 STREET,14:40,4129283,Sedan,Sedan,NaN,NaN,NaN,11232.0
991,NaN,Fell Asleep,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.713654,-74.011720,...,NaN,GREENWICH STREET,14:05,4129388,Sedan,Sedan,NaN,NaN,NaN,NaN
992,NaN,Passing Too Closely,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.853580,-73.932236,...,NaN,WADSWORTH AVENUE,18:15,4130929,Sedan,Van,NaN,NaN,NaN,NaN
993,BRONX,Unsafe Lane Changing,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.885952,-73.827900,...,CONNER STREET,BOSTON ROAD,19:00,4131062,Sedan,Sedan,NaN,NaN,NaN,10475.0
994,NaN,Unspecified,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,NaN,NaN,...,NaN,HUTCHINSON RIVER PARKWAY RAMP,14:50,4130664,Sedan,Bus,NaN,NaN,NaN,NaN
995,MANHATTAN,Passing or Lane Usage Improper,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,NaN,NaN,...,5TH AVE,EAST 8TH,1:30,4128877,Taxi,Bike,NaN,NaN,NaN,10003.0
996,QUEENS,Unspecified,Unspecified,Unspecified,Unspecified,NaN,NaN,2019-05-10,40.669216,-73.750050,...,MENTONE AVENUE,225 STREET,16:45,4129308,Sedan,Sedan,Sedan,Sedan,NaN,11413.0
997,NaN,Following Too Closely,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.688920,-73.999150,...,NaN,BROOKLYN QUEENS EXPRESSWAY,14:25,4131143,Station Wagon/Sport Utility Vehicle,Taxi,NaN,NaN,NaN,NaN
998,BROOKLYN,Traffic Control Disregarded,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.673164,-73.904850,...,LIBERTY AVENUE,POWELL STREET,10:00,4131363,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN,11212.0
999,NaN,Driverless/Runaway Vehicle,Unspecified,NaN,NaN,NaN,NaN,2019-05-10,40.769610,-73.831505,...,NaN,137 STREET,13:10,4129337,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN